POST http://localhost:8080/api/purchase/
Content-Type: application/json

{
  "name": "sub1",
  "url": "http://localhost:8090/api/subscription/"
}

### отправить сообщения
GET http://localhost:8080/api/purchase/notify
